### ISSUE TITLE
Nl term for the sun's highest point is zenith

### ISSUE THREAD

**Issue by FransOv** [edwardtfn/home-assistant-sun-card#14]
Very nice card, goes well with weather and solar panel info. Only one issue: The Dutch ter for when the sun is at it's highest point is "Zenith". "Zonne-middag" is never used.

**Comment by edwardtfn** [comment]
Please take a look at the notice about the future of this repository: https://github.com/edwardtfn/home-assistant-sun-card#notice-about-the-future-of-this-repository

**Comment by FransOv** [comment]
Thank you for redirecting me to the correct repository.
