### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by Rossano95** [edwardtfn/home-assistant-sun-card#9]
Hi, I just changed the Dawn translation from Alba to Aurora and translated the error.
Thank you for your work.

{
  "Azimuth": "Azimuth",
  "Dawn": "Aurora",
  "Dusk": "Crepuscolo",
  "Elevation": "Elevazione",
  "Noon": "Mezzogiorno solare",
  "Sunrise": "Alba",
  "Sunset": "Tramonto",
  "errors": {
    "SunIntegrationNotFound": "Integrazione Sun non trovata"
  }
}

**Comment by Rossano95** [comment]
There is also this line:
"SunIntegrationNotFound": "Integrazione Sun non trovata"
The other lines are correct.

**Comment by edwardtfn** [comment]
Done!
